apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    name: telegraf
spec:
  selector:
    app: telegraf
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
spec:
  selector:
    matchLabels:
      app: telegraf
  replicas: 1
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccountName: telegraf-account
      containers:
      - name: telegraf
        image: telegraf
        imagePullPolicy: Never

---
#Here, we bind the telegraf-account to the cluster-admin role.
#It allows telegraf process to have full permissions all over the cluster so it can
#get all the metrics from every services.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: telegraf-account
  namespace: default

---
#A service account is an identifier for a process in a cluster. Here, we identify the telegraf
#process as telegraf-account. Then we can bin this process to a cluster role to give it special
#privileges accross the cluster.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-account
  labels:
    app: telegraf